### PR TITLE
release: 0.2.0 (take two)

### PR DESCRIPTION
**Pull request by nicholasbishop**
Add repository URL and description to the cargo metadata.

### CODE REVIEW

**Review by phil-opp — APPROVED** [review]

**Review by phip1611 — APPROVED** [review]

**Comment by phip1611** [comment]
@nicholasbishop Now it failed because of missing permissions

https://github.com/rust-osdev/ovmf-prebuilt/actions/runs/11496371450/job/31998026962

**Comment by nicholasbishop** [comment]
Ah right, I missed an important step :)

@phil-opp could you add me as an owner on the [ovmf-prebuilt](https://crates.io/crates/ovmf-prebuilt) crate?

**Comment by phip1611** [comment]
Wouldn't it make more sense to add a github team as owner instead of individual people?

**Comment by phil-opp** [comment]
I just added `github:rust-osdev:uefi` as owner. I hope this syntax was correct. Thanks for your work in this!

**Comment by nicholasbishop** [comment]
Confirmed that worked, thanks :)

**Pull request merged**
